[build-system]
# Should be mirrored in requirements-build.txt
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"


[project.urls]
homepage = "https://github.com/DeJoker/pybragi" 

[project]
name = "pybragi"
version = "0.0.4"
description = "pybragi is server framework"
authors = [
    {name = "DeJoker", email = "localjie@163.com"},
]
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "facebook-scribe==2.0.post1",
    "thrift",
    "pydantic",
    "psutil>=5.9.1",
    "tornado>=6.0.2",
    "pymongo>=3.4.0",
    "ujson>=1.35",
    "kafka-python>=2.0.2",
    "requests>=2.22.0",
    "prometheus_client>=0.14.1",
    "facebook-scribe==2.0.post1",
    "opencv-python>=4.4.0",
    "numpy",
    "pillow",
    "uvicorn",
    "nvidia-ml-py",
    "GPUtil",
]

[tool.poetry]
repository = "https://github.com/DeJoker/pybragi"



[tool.setuptools.packages.find]
include = ["pybragi*"] 
exclude = ["assets*", "benchmark*", "docs*", "dist*", "demo*", "tests*",]

[project.optional-dependencies]
base = ["fastapi",
       ]
openai = ["openai>=1.0", "tiktoken"]
anthropic = ["anthropic>=0.20.0"]
litellm = ["litellm>=1.0.0"]
test = ["jsonlines", "matplotlib", "pandas"]
all = ["pybragi[srt]", "pybragi[openai]", "pybragi[anthropic]", "pybragi[litellm]"]
dev = ["pybragi[all]", "pybragi[test]"]
